# Generated by Django 5.2.7 on 2025-10-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_deals', to='store.product', verbose_name='Товар дня')),
            ],
            options={
                'verbose_name': 'Товар дня',
                'verbose_name_plural': 'Товары дня',
                'ordering': ['-added_at'],
            },
        ),
    ]
