# Generated by Django 5.2.7 on 2025-11-10 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_product_options_cart_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название ПВЗ")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Широта"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Пункт выдачи",
                "verbose_name_plural": "Пункты выдачи",
            },
        ),
        migrations.CreateModel(
            name="OrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Самовывоз со склада"),
                            ("pvz", "Доставка в ПВЗ"),
                        ],
                        max_length=20,
                        verbose_name="Тип доставки",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card_now", "Картой сразу"),
                            ("card_on_delivery", "Картой при получении"),
                        ],
                        max_length=20,
                        verbose_name="Оплата",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "accept_terms",
                    models.BooleanField(
                        default=False, verbose_name="Согласие с условиями"
                    ),
                ),
                ("cart_snapshot", models.JSONField(verbose_name="Состав заказа")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма заказа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "status",
                    models.CharField(
                        default="new", max_length=50, verbose_name="Статус"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "pickup_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.pickuppoint",
                        verbose_name="ПВЗ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на заказ",
                "verbose_name_plural": "Заявки на заказ",
                "ordering": ["-created_at"],
            },
        ),
    ]
