# Generated by Django 5.2.7 on 2025-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_pickuppoint_orderrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["main_category", "name"],
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="category",
            name="main_category",
            field=models.CharField(
                choices=[
                    ("spare_parts", "Автозапчасти"),
                    ("tires", "Шины"),
                    ("rims", "Диски"),
                    ("batteries", "Аккумуляторы"),
                    ("car_chemicals", "Автохимия"),
                    ("accessories", "Аксессуары"),
                    ("tools", "Инструменты"),
                    ("wipers", "Щётки"),
                    ("electronics", "Электроника"),
                ],
                default="spare_parts",
                max_length=32,
                verbose_name="Главная категория",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("main_category", "name")},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Подкатегория"),
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
