# Generated by Django 5.2.7 on 2025-11-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="⚙️", max_length=8, verbose_name="Иконка/эмодзи"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название блока"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Раздел автозапчастей",
                "verbose_name_plural": "Разделы автозапчастей",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SparePartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название позиции"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.sparepartsection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция раздела автозапчастей",
                "verbose_name_plural": "Позиции разделов автозапчастей",
                "ordering": ["section", "order", "id"],
            },
        ),
    ]
