# Generated by Django 5.2.7 on 2025-11-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_seed_spare_parts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_category",
                    models.CharField(
                        choices=[
                            ("spare_parts", "Автозапчасти"),
                            ("tires", "Шины"),
                            ("rims", "Диски"),
                            ("batteries", "Аккумуляторы"),
                            ("car_chemicals", "Автохимия"),
                            ("accessories", "Аксессуары"),
                            ("tools", "Инструменты"),
                            ("wipers", "Щётки"),
                            ("electronics", "Электроника"),
                        ],
                        max_length=32,
                        verbose_name="Главная категория",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название группы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Группа подкатегорий",
                "verbose_name_plural": "Группы подкатегорий",
                "ordering": ["main_category", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="store.categorygroup",
                verbose_name="Группа",
            ),
        ),
    ]
