# Generated by Django 5.2.7 on 2025-11-12 07:58

import django.db.models.deletion
from django.db import migrations, models


def create_initial_specs(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    AutoPartSpecification = apps.get_model("store", "AutoPartSpecification")

    for product in Product.objects.all():
        AutoPartSpecification.objects.get_or_create(product=product)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_categorygroup_category_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("auto_part", "Автозапчасть"), ("auto_goods", "Автотовар")],
                default="auto_part",
                max_length=20,
                verbose_name="Тип товара",
            ),
        ),
        migrations.CreateModel(
            name="AutoGoodsSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_code",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Артикул / Код"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Бренд / Производитель"
                    ),
                ),
                (
                    "volume_or_weight",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Объём / Вес"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Размер (Д×Ш×В)"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Материал"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=255, verbose_name="Цвет"),
                ),
                (
                    "compatibility",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Совместимость / Универсальность",
                    ),
                ),
                (
                    "temperature_range",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Температурный диапазон",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Страна производства"
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Гарантия"
                    ),
                ),
                (
                    "package_contents",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комплектация"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_goods_spec",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики автотовара",
                "verbose_name_plural": "Характеристики автотоваров",
            },
        ),
        migrations.CreateModel(
            name="AutoPartSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oem_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="OEM / Оригинальный номер",
                    ),
                ),
                (
                    "manufacturer_article",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Артикул производителя"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Бренд / Производитель"
                    ),
                ),
                (
                    "compatibility",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Совместимость (марка, модель, год)",
                    ),
                ),
                (
                    "installation_side",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Сторона установки"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Материал"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Вес, кг",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Габариты (Д×Ш×В)"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Страна производства"
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Гарантия"
                    ),
                ),
                (
                    "certificates",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Сертификаты / Стандарты",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_part_spec",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики автозапчасти",
                "verbose_name_plural": "Характеристики автозапчастей",
            },
        ),
        migrations.RunPython(create_initial_specs, migrations.RunPython.noop),
    ]
