# Generated by Django 5.2.7 on 2025-11-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_product_type_autogoodsspecification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=120, verbose_name="Марка")),
                ("model", models.CharField(max_length=120, verbose_name="Модель")),
                (
                    "generation",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Поколение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["make", "model", "generation"],
                "unique_together": {("make", "model", "generation")},
            },
        ),
    ]
