# Generated by Django 5.2.7 on 2025-11-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_car"),
    ]

    def generate_ford_cars(apps, schema_editor):
        Car = apps.get_model("store", "Car")
        entries = [
            ("Ford", "Focus", "Mk I (1998–2004)"),
            ("Ford", "Focus", "Mk II (2004–2011)"),
            ("Ford", "Focus", "Mk III (2011–2018)"),
            ("Ford", "Focus", "Mk IV (2018–2021)"),
            ("Ford", "Focus", "Mk IV Facelift (2021–2023)"),
            ("Ford", "Fiesta", "Mk V (2002–2008)"),
            ("Ford", "Fiesta", "Mk VI (2008–2017)"),
            ("Ford", "Fiesta", "Mk VII (2017–2023)"),
            ("Ford", "Fiesta", "Mk VII Facelift (2021–2023)"),
            ("Ford", "Fusion", "Mk I Europe (2002–2012)"),
            ("Ford", "Fusion", "Mk I North America (2006–2012)"),
            ("Ford", "Fusion", "Mk II (2013–2016)"),
            ("Ford", "Fusion", "Mk II Facelift (2017–2020)"),
            ("Audi", "A2", "8Z0 (1999–2005)"),
            ("Audi", "A4", "B5 (1994–2001)"),
            ("Audi", "A4", "B6 (2000–2006)"),
            ("Audi", "A4", "B7 (2004–2008)"),
            ("Audi", "A4", "B8 (2008–2015)"),
            ("Audi", "A4", "B9 (2015–2023)"),
            ("Audi", "A5", "8T (2007–2016)"),
            ("Audi", "A5", "F5 (2016–2020)"),
            ("Audi", "A5", "F5 Facelift (2020–2023)"),
            ("Audi", "A6", "C5 (1997–2004)"),
            ("Audi", "A6", "C6 (2004–2011)"),
            ("Audi", "A6", "C7 (2011–2018)"),
            ("Audi", "A6", "C8 (2018–2023)"),
            ("Kia", "Rio", "II (JB, 2005–2011)"),
            ("Kia", "Rio", "III (UB, 2011–2017)"),
            ("Kia", "Rio", "IV (FB, 2017–2022)"),
            ("Kia", "Rio", "IV Facelift (2023–present)"),
            ("Kia", "Ceed", "JD (2012–2018)"),
            ("Kia", "Ceed", "CD (2018–2023)"),
            ("Kia", "Sportage", "QL (2015–2021)"),
            ("Kia", "Sportage", "NQ5 (2021–present)"),
            ("Kia", "Sorento", "UM (2014–2020)"),
            ("Kia", "Sorento", "MQ4 (2020–present)"),
        ]
        for make, model, generation in entries:
            Car.objects.get_or_create(
                make=make,
                model=model,
                generation=generation,
            )

    def delete_ford_cars(apps, schema_editor):
        Car = apps.get_model("store", "Car")
        Car.objects.filter(make__in=["Ford", "Audi", "Kia"]).delete()

    operations = [
        migrations.RunPython(generate_ford_cars, delete_ford_cars),
    ]
