# Generated by Django 5.2.7 on 2025-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_seed_ford_cars"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="compatible_cars",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="store.car",
                verbose_name="Совместимые автомобили",
            ),
        ),
    ]
