# Generated by Django 5.2.7 on 2025-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_product_compatible_cars"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuppoint",
            name="company",
            field=models.CharField(blank=True, max_length=120, verbose_name="Компания"),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="working_hours",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Время работы"
            ),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
