# Generated by Django 5.2.7 on 2025-11-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_pickuppoint_company_pickuppoint_working_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество на складе"
            ),
        ),
    ]
