# Generated by Django 5.2.7 on 2025-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_product_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание бренда"),
        ),
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="brands/", verbose_name="Изображение"
            ),
        ),
    ]
