# Generated by Django 5.2.7 on 2025-11-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_uservehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("auto_part", "Автозапчасть"),
                    ("auto_goods", "Автотовар"),
                    ("tires", "Шины"),
                ],
                default="auto_part",
                max_length=20,
                verbose_name="Тип товара",
            ),
        ),
        migrations.CreateModel(
            name="TireSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Ширина (мм)"
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Профиль (%)"
                    ),
                ),
                (
                    "diameter",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Диаметр (R)"
                    ),
                ),
                (
                    "load_index",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Индекс нагрузки"
                    ),
                ),
                (
                    "speed_index",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Индекс скорости"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("summer", "Летняя"),
                            ("winter", "Зимняя"),
                            ("all_season", "Всесезонная"),
                        ],
                        default="summer",
                        max_length=16,
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "stud_type",
                    models.CharField(
                        choices=[
                            ("studded", "Шипованная"),
                            ("friction", "Липучка"),
                            ("none", "Без шипов"),
                        ],
                        default="none",
                        max_length=16,
                        verbose_name="Шипы / липучка",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Страна производства"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tire_spec",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики шины",
                "verbose_name_plural": "Характеристики шин",
            },
        ),
    ]
