# Generated by Django 5.2.7 on 2025-11-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_alter_product_product_type_tirespecification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tirespecification",
            name="diameter",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Диаметр (R)"
            ),
        ),
        migrations.AlterField(
            model_name="tirespecification",
            name="load_index",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Индекс нагрузки"
            ),
        ),
        migrations.AlterField(
            model_name="tirespecification",
            name="profile",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Профиль (%)"
            ),
        ),
        migrations.AlterField(
            model_name="tirespecification",
            name="speed_index",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Индекс скорости"
            ),
        ),
        migrations.AlterField(
            model_name="tirespecification",
            name="width",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Ширина (мм)"
            ),
        ),
    ]
