# Generated by Django 5.2.7 on 2025-11-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_tirespecification_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('auto_part', 'Автозапчасть'), ('auto_goods', 'Автотовар'), ('tires', 'Шины'), ('rims', 'Диски')], default='auto_part', max_length=20, verbose_name='Тип товара'),
        ),
        migrations.CreateModel(
            name='RimSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.CharField(blank=True, max_length=16, verbose_name='Диаметр (R)')),
                ('width', models.CharField(blank=True, max_length=16, verbose_name='Ширина обода')),
                ('pcd', models.CharField(blank=True, max_length=32, verbose_name='PCD (кол-во×диаметр)')),
                ('center_bore', models.CharField(blank=True, max_length=16, verbose_name='Центральное отверстие')),
                ('offset', models.CharField(blank=True, max_length=16, verbose_name='Вылет (ET)')),
                ('material', models.CharField(blank=True, max_length=64, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=64, verbose_name='Цвет')),
                ('country_of_origin', models.CharField(blank=True, max_length=255, verbose_name='Страна производства')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rim_spec', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристики диска',
                'verbose_name_plural': 'Характеристики дисков',
            },
        ),
    ]
