# Generated by Django 5.2.7 on 2025-11-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_product_product_type_rimspecification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("auto_part", "Автозапчасть"),
                    ("auto_goods", "Автотовар"),
                    ("tires", "Шины"),
                    ("rims", "Диски"),
                    ("batteries", "Аккумуляторы"),
                ],
                default="auto_part",
                max_length=20,
                verbose_name="Тип товара",
            ),
        ),
        migrations.CreateModel(
            name="BatterySpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity_ah",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Ёмкость (А·ч)"
                    ),
                ),
                (
                    "cold_cranking_amps",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Пусковой ток (A)"
                    ),
                ),
                (
                    "voltage",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Напряжение (В)"
                    ),
                ),
                (
                    "polarity",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Полярность"
                    ),
                ),
                (
                    "terminal_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Тип клемм"
                    ),
                ),
                (
                    "length_mm",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Длина (мм)"
                    ),
                ),
                (
                    "width_mm",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Ширина (мм)"
                    ),
                ),
                (
                    "height_mm",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Высота (мм)"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Страна производства"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_spec",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики аккумулятора",
                "verbose_name_plural": "Характеристики аккумуляторов",
            },
        ),
    ]
