# Generated by Django 5.2.7 on 2025-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер'), ('admin', 'Администратор')], max_length=255, unique=True),
        ),
    ]
